package com.example.android.miwok;

/**body, city, colors, house, school, shop, sport,time,family,verbs
 *
 * do zrobienia: food, numbers, phrases, travels
 *
 * Created by Madeleine Katherine on 21.01.2018.
 */

public class QuestionActivity {
    public String mQuestion[]={
         "die Stadt",
            "das Restaurant",/*3*/
            "die Straße",/*4*/
            "die Post",/*5*/
            "der Flughafen",
      "der Geldautomat",/*7*/
            "das Kino",/*8*/
            "das Krankenhaus",/*9*/
            "das Museum",
            "der Parkplatz",/*11*/
            "das Schwimmbad",/*12*/
            "der Park",/*13*/
            "die Bibliothek",
       /*14*/     "der Bahnhof",/*15*/
            "die Bushaltestelle",
            "city",
            "restaurant",
            "street",
            "post",
            "airport",
            "ATM",
            "cinema",
            "hospital",
            "museum",
            "parking",
            "swimming pool",
            "park",
            "library",
            "railway station",
            "bus stop",
            "head",
            "arm",
            "leg",
            "mouth",
            "nose",
            "eye",
            "ear",
            "hair",
            "shoulder",
            "knee",
            "der Kopf",
            "der Arm",
            "das Bein",
            "der Mund",
            "die Nase",
            "das Auge",
            "das Ohr",
            "das Haar",
            "die Schulter",
            "das Knie",
            "red",
            "yellow",
            "green",
            "brown",
            "grey",
            "white",
            "black",
            "blue",

            "rot",
            "gelb",
            "grün",
            "braun",
            "grau",
            "weiß",
            "schwarz",
            "blau",

            "window",
            "clock",
            "lamp",
            "table",
            "armchair",
            "mirror",
            "toilet",
            "picture",
            "1st floor",
            "fridge",
            "dishes",
            "kitchen",
            "bathroom",
            "living room",
            "furniture",
            "desk",
            "bedroom",
            "door",


            "das Fenster",
            "die Uhr",
            "die Lampe",
            "der Tisch",
            "der Sessel",
            "der Spiegel",
            "die Toilette",
            "das Bild",
            "der erste Stock",
            "der Kühlschrank",
            "das Geschirr",
            "die Küche",
            "das Badezimmer",
            "das Wohnzimmer",
            "die Möbel",
            "der Schreibtisch",
            "das Schlafzimmer",
            "die Tür",

            "english",
            "mathematics",
            "french",
            "spanish",
            "german",
            "physics",
            "chemistry",
            "biology",
            "art",
            "geography",
            "physicacl education (PE)",
            "teacher",
            "classroom",

            "das Englisch",
            "die Mathe",
            "das Französich",
            "das Spanisch",
            "das Deutsch",
            "die Physik",
            "die Chemie",
            "die Biologie",
            "die Kunst",
            "die Erdkunde",
            "der Sport",
            "der Lehrer/die Lehrerin",
            "das Klassenzimmer",

            "supermarket",
            "grocer's",
            "baker's",
            "cake shop",
            "chemist's",
            "book shop",
            "shoe shop",
            "perfume shop",
            "opening hours",
            "jeweller's",
            "special offer",
            "closed",
            "open",
            "entrance",
            "exit",
            "cash desk",
            "florist's",


            "der Supermarkt",
            "das Lebensmittelgeschäft",
            "die Bäckerei",
            "die Konditorei",
            "die Drogerie",
            "die Buchhandlung",
            "das Schuhgeschäft",
            "die Perfümerie",
            "die Öffnungzeiten",
            "der Juwelierladen",
            "das Sonderangebot",
            "geschlossen",
            "geöffnet",
            "der Eingang",
            "der Ausgang",
            "die Kasse",
            "die Blumengeschäft",

            "alpine skiing",
            "archery",
            "baseball",
            "boxing",
            "bungee jumping",
            "caving",
            "cycling",
            "diving",
            "football/soccer",
            "skiing",
            "table tennis",


            "der Ski alpin",
            "das Bogenschießen",
            "der Baseball",
            "das Boxen",
            "das Bungee springen",
            "die Höhlenforschung",
            "der Radsport",
            "das Wasserspringen",
            "der Fußball",
            "das Skilaufen",
            "das Tischtennis",

            "time",
            "hour",
            "minute",
            "second",
            "midnight",
            "midday",
            "day",
            "morning",
            "afternoon",
            "night",
            "yesterday",
            "today",
            "tommorow",
            "spring",
            "winter",
            "summer",
            "autumn",

            "die Zeit",
            "die Stunde",
            "die Minute",
            "die Sekunde",
            "die Mitternacht",
            "der Mittag",
            "der Tag",
            "der Morgen",
            "der Nachmittag",
            "die Nacht",
            "gestern",
            "heute",
            "morgen",
            "der Frühling",
            "der Winter",
            "der Sommer",
            "der Herbst",

            "family",
            "father",
            "mother",
            "son",
            "daughter",
            "brother",
            "sister",
            "grandmother",
            "grandfather",

            "die Familie",
            "der Vater",
            "die Mutter",
            "der Sohn",
            "die Tochter",
            "der Bruder",
            "die Schwester",
            "die Großmutter",
            "der Großvater",

            "to do",
            "to be",
            "to have",
            "to work",
            "to see",
            "to sleep",
            "to drink",
            "to eat",
            "to feel",

            "machen",
            "sein",
            "haben",
            "arbeiten",
            "sehen",
            "schlafen",
            "trinken",
            "essen",
            "fühlen",

            "ein",
            "zwei",
            "drei",
            "vier",
            "fünf",
            "sechs",
            "sieben",
            "acht",
            "neun",
            "zehn",

            "one",
            "two",
            "three",
            "four",
            "five",
            "six",
            "seven",
            "eight",
            "nine",
            "ten",

            "Good morning!",
            "Good afternoon!",
            "Goodbye!",
            "Where are you from?",
            "What's your name?",
            "My name is/ I am ...",
            "How old are you?",
            "I'm ... years old.",
            "Where do you live?",
            "I live in...",
            "How can I get to...?",
            "Turn left.",
            "Turn right.",
            "Go straight ahead.",
            "I'm lost.",

            "Guten Morgen",
            "Guten Tag!",
            "Auf Wiedersehen!",
            "Woher kommst du?",
            "Wie heißt du?",
            "Ich heiße/ Ich bin...?",
            "Wie alt bist du?",
            "Ich bin ... Jahre alt.",
            "Wo wohnst du?",
            "Ich wohne in...",
            "Wie komme ich zu...?",
            "Nach links.",
            "Nach rechts.",
            "Geradeaus gehen.",
            "Ich habe mich verirrt.",

            "meat",
            "chicken",
            "ham",
            "sausage",
            "apple",
            "orange",
            "strawbery",
            "raspberry",
            "grape",
            "tomato",
            "potato",
            "carrot",
            "onion",
            "pear",
            "watermelon",
            "cheese",
            "milk",
            "butter",
            "rice",
            "pasta",
            "bread",

            "das Fleisch",
            " das Hänchen",
            "der Schinken",
            "die Wurst",
            "der Apfel",
            "die Orange",
            "die Erdbeere",
            "die Himbeere",
            "die Traube",
            "die Tomate",
            "die Kartoffel",
            "die Karrotten",
            "die Zwiebel",
            "die Birne",
            "die Wassermelone",
            "der Käse",
            "die Milch",
            "die Butter",
            "der Reis",
            "die Nudeln",
            "das Brot",

            "der Flughafen",
            "der Geldautomat",
            "das Museum",
            "der Bahnhof",
            "die Bushaltestelle",
            "der Flugschein",
            "der Rucksack",
            "der Koffer",
            "der Zoll",
            "das Gepäck",
            "die Fahrkarte",
            "die Reservierung",
            "der Reisepass",
            "der Flug",
            "die Rezeption",

            "airport",
            "ATM",
            "museum",
            "railway station",
            "bus stop",
            "airplane ticket",
            "backpack",
            "suitcase",
            "customs",
            "baggage",
            "ticket",
            "reservation",
            "passport",
            "flight",
            "recepiton desk"
    };

    private String mChoices[][]={
         /*1*/   {"post", "city", "railway station"},
         /*2*/   {"restaurant","parking","park"},
         /*3*/   {"street","library","cinema"},
         /*4*/   {"city","airport","post"},
         /*5*/   {"airport","parking","ATM"},
         /*6*/   {"restaurant","ATM","library"},
         /*7*/   {"street","cinema","park"},
         /*8*/   {"hospital","parking","park"},
         /*9*/   {"parking","museum","library"},
         /*10*/   {"ATM","parking","city"},
         /*11*/   {"swimming pool","bus stop","park"},
         /*12*/   {"library","street","park"},
         /*13*/   {"library","swimming pool","bus stop"},
         /*14*/   {"bus stop","railway station","park"},
         /*15*/   {"airport","bus stop","city"},
            {"die Post", "die Stadt", "das Museum"},
            {"der Geldautomat", "das Restaurant","der Flughafen"},
            {"die Straße", "die Stadt", "das Kino"},
            {"die Post", "die Stadt", "das Museum"},
            {"der Geldautomat", "die Straße","der Flughafen"},
            {"das Krankenhaus", "die Stadt", "der Geldautomat"},
            {"das Kino", "der Parkplatz", "das Museum"},
            {"das Krankenhaus", "die Straße","der Flughafen"},
            {"das Krankenhaus", "die Stadt", "das Museum"},
            {"der Parkplatz", "die Stadt", "das Museum"},
            {"das Schwimmbad", "die Straße","der Bahnhof"},
            {"das Krankenhaus", "die Bushaltestelle", "der Park"},
            {"die Bibliothek", "die Stadt", "das Museum"},
            {"der Geldautomat", "die Straße","der Bahnhof"},
            {"das Krankenhaus", "die Bushaltestelle", "das Kino"},
            {"das Auge", "der Kopf", "der Arm"},
            {"der Arm", "die Nase", "das Ohr"},
            {"das Knie", "das Bein", "das Haar"},
            {"der Mund", "die Nase", "das Bein"},
            {"der Kopf", "die Nase", "das Ohr"},
            {"der Mund", "die Nase", "das Auge"},
            {"der Kopf", "die Nase", "das Ohr"},
            {"der Mund", "das Haar", "das Ohr"},
            {"der Arm", "die Schulter", "das Knie"},
            {"das Knie", "die Nase", "das Ohr"},
            {"arm","mouth","head"},
            {"nose","ear","arm"},
            {"hair","leg","knee"},
            {"nose","mouth","shoulder"},
            {"arm","nose","leg"},
            {"eye","mouth","head"},
            {"arm","eye","ear"},
            {"shoulder","mouth","hair"},
            {"arm","shoulder","eye"},
            {"leg","mouth","knee"},

            {"rot","gelb","blau"},
            {"blau","schwarz","gelb"},
            {"grün","weiß","rot"},
            {"braun","weiß","blau"},
            {"grün","grau","gelb"},
            {"schwarz","weiß","grau"},
            {"rot","weiß","schwarz"},
            {"schwarz","rot","blau"},

            {"red","yellow","white"},
            {"grey","yellow","green"},
            {"green","blue","red"},
            {"brown","red","yellow"},
            {"yellow","grey","blue"},
            {"black","white","green"},
            {"green","black","white"},
            {"blue","white","red"},

            {"die Uhr","der Tisch","das Fenster"},
            {"die Uhr","der Spiegel","das Fenster"},
            {"die Toilette","die Lampe","der erste Stock"},
            {"der Sessel","das Schlafzimmer","der Tisch"},
            {"der Sessel","das Bild","das Geschirr"},
            {"die Tür","der Spiegel","das Bild"},
            {"die Toilette","das Badezimmer","das Geschirr"},
            {"der Spiegel","das Bild","die Uhr"},
            {"der erste Stock","das Schlafzimmer","das Geschirr"},
            {"der Kühlschrank","die Küche","die Möbel"},
            {"die Toilette","das Badezimmer","das Geschirr"},
            {"der Kühlschrank","die Küche","die Möbel"},
            {"die Toilette","das Badezimmer","das Geschirr"},
            {"das Badezimmer","das Wohnzimmer","die Toilette"},
            {"der Kühlschrank","die Küche","die Möbel"},
            {"der Schreibtisch","der Tisch","die Tür"},
            {"der erste Stock","das Schlafzimmer","das Geschirr"},
            {"der Schreibtisch","der Tisch","die Tür"},

            {"clock","window","armchair"},
            {"clock","window","armchair"},
            {"mirror","lamp","picture"},
            {"table","desk","fridge"},
            {"clock","window","armchair"},
            {"mirror","lamp","picture"},
            {"toilet","bathroom","dishes"},
            {"mirror","lamp","picture"},
            {"1st floor","bedroom","door"},
            {"table","desk","fridge"},
            {"toilet","bathroom","dishes"},
            {"kitchen","living room","furniture"},
            {"toilet","bathroom","dishes"},
            {"kitchen","living room","furniture"},
            {"kitchen","living room","furniture"},
            {"table","desk","fridge"},
            {"1st floor","bedroom","door"},
            {"1st floor","bedroom","door"},

            {"das Englisch","die Erdkunde","die Kunst"},
            {"die Mathe","die Chemie","die Physik"},
            {"das Französich","das Deutsch","das Spanisch"},
            {"das Französich","das Deutsch","das Spanisch"},
            {"das Französich","das Deutsch","das Spanisch"},
            {"die Mathe","die Chemie","die Physik"},
            {"die Mathe","die Chemie","die Physik"},
            {"die Biologie","der Lehrer/die Lehrerin", "das Klassenzimmer"},
            {"das Englisch","die Erdkunde","die Kunst"},
            {"das Englisch","die Erdkunde","die Kunst"},
            {"die Kunst", "die Mathe","der Sport"},
            {"die Biologie","der Lehrer/die Lehrerin", "das Klassenzimmer"},
            {"die Biologie","der Lehrer/die Lehrerin", "das Klassenzimmer"},

            {"english","french","spanish"},
            {"physics","mathematics", "chemistry"},
            {"english","french","spanish"},
            {"english","french","spanish"},
            {"german","art","geography"},
            {"physics","mathematics", "chemistry"},
            {"physics","mathematics", "chemistry"},
            {"biology","chemistry", "german"},
            {"german","art","geography"},
            {"german","art","geography"},
            {"physicacl education (PE)", "teacher", "classroom"},
            {"physicacl education (PE)", "teacher", "classroom"},
            {"physicacl education (PE)", "teacher", "classroom"},

            {"der Supermarkt","die Bäckerei","der Juwelierladen"},
            {"das Lebensmittelgeschäft","die Buchhandlung","das Schuhgeschäft"},
            {"der Supermarkt","die Bäckerei","der Juwelierladen"},
            {"die Drogerie","die Perfümerie","die Konditorei"},
            {"die Drogerie","die Perfümerie","die Konditorei"},
            {"das Lebensmittelgeschäft","die Buchhandlung","das Schuhgeschäft"},
            {"das Lebensmittelgeschäft","die Buchhandlung","das Schuhgeschäft"},
            {"die Drogerie","die Perfümerie","die Konditorei"},
            {"die Öffnungzeiten","geöffnet","geschlossen"},
            {"der Supermarkt","die Bäckerei","der Juwelierladen"},
            {"der Eingang","der Ausgang","das Sonderangebot"},
            {"die Öffnungzeiten","geöffnet","geschlossen"},
            {"die Öffnungzeiten","geöffnet","geschlossen"},
            {"der Eingang","der Ausgang","das Sonderangebot"},
            {"der Eingang","der Ausgang","das Sonderangebot"},
            {"die Kasse","der Ausgang","die Konditorei"},
            {"die Blumengeschäft","die Buchhandlung","das Schuhgeschäft"},

            {"supermarket","grocer's","special offer"},
            {"supermarket","grocer's","special offer"},
            {"baker's", "shoe shop","book shop"},
            {"cash desk","opening hours","cake shop"},
            {"chemist's","shoe shop","entrance"},
            {"book shop","entrance","cake shop"},
            {"chemist's","shoe shop","entrance"},
            {"jeweller's","florist's","perfume shop"},
            {"cash desk","opening hours","cake shop"},
            {"jeweller's","florist's","perfume shop"},
            {"supermarket","grocer's","special offer"},
            {"closed","open","exit"},
            {"closed","open","exit"},
            {"chemist's","shoe shop","entrance"},
            {"closed","open","exit"},
            {"cash desk","opening hours","cake shop"},
            {"jeweller's","florist's","perfume shop"},

            {"der Ski alpin","der Radsport","das Skilaufen"},
            {"das Bogenschießen","das Bungee springen","das Wasserspringen"},
            {"der Baseball","der Fußball","das Tischtennis"},
            {"das Boxen","die Höhlenforschung","der Radsport"},
            {"das Bogenschießen","das Bungee springen","das Wasserspringen"},
            {"das Boxen","die Höhlenforschung","der Radsport"},
            {"der Ski alpin","der Radsport","das Skilaufen"},
            {"das Bogenschießen","das Bungee springen","das Wasserspringen"},
            {"der Baseball","der Fußball","das Tischtennis"},
            {"der Ski alpin","der Radsport","das Skilaufen"},
            {"der Baseball","der Fußball","das Tischtennis"},

            {"alpine skiing","skiing","cycling"},
            {"archery","diving","caving"},
            {"baseball", "boxing","football/soccer"},
            {"baseball", "boxing","football/soccer"},
            {"bungee jumping","table tennis","diving"},
            {"archery","diving","caving"},
            {"alpine skiing","skiing","cycling"},
            {"archery","diving","caving"},
            {"baseball", "boxing","football/soccer"},
            {"alpine skiing","skiing","cycling"},
            {"bungee jumping","table tennis","diving"},

            {"die Zeit","die Stunde","der Tag"},
            {"die Zeit","die Stunde","der Tag"},
            {"die Sekunde","die Minute","der Tag"},
            {"die Sekunde","die Minute","der Tag"},
            {"der Mittag","die Mitternacht","der Nachmittag"},
            {"der Mittag","die Mitternacht","der Nachmittag"},
                    {"die Zeit","die Stunde","der Tag"},
            {"die Nacht","der Morgen","der Herbst"},
            {"der Mittag","die Mitternacht","der Nachmittag"},
            {"die Nacht","der Morgen","der Herbst"},
            {"gestern","heute","morgen"},
            {"gestern","heute","morgen"},
            {"gestern","heute","morgen"},
            {"der Frühling","der Winter","der Sommer"},
            {"der Frühling","der Winter","der Sommer"},
            {"der Frühling","der Winter","der Sommer"},
            {"die Nacht","der Morgen","der Herbst"},

            {"time","hour","day"},
            {"time","hour","day"},
            {"minute","time","second"},
            {"minute","time","second"},
            {"midnight","midday","afternoon"},
            {"midnight","midday","afternoon"},
            {"time","hour","day"},
            {"night","autumn","morning"},
            {"midnight","midday","afternoon"},
            {"night","autumn","morning"},
            {"yesterday","tommorow","today"},
            {"yesterday","tommorow","today"},
            {"yesterday","tommorow","today"},
            {"spring","winter","summer"},
            {"spring","winter","summer"},
            {"spring","winter","summer"},
            {"night","autumn","morning"},

            {"die Familie","die Mutter","der Bruder"},
            {"der Sohn","der Großvater","der Vater"},
            {"die Familie","die Mutter","der Bruder"},
            {"der Sohn","der Großvater","der Vater"},
            {"die Tochter","die Schwester","die Großmutter"},
            {"die Familie","die Mutter","der Bruder"},
            {"die Tochter","die Schwester","die Großmutter"},
            {"die Tochter","die Schwester","die Großmutter"},
            {"der Sohn","der Großvater","der Vater"},

            {"family","father","grandmother"},
            {"family","father","grandmother"},
            {"daughter","sister","mother"},
            {"son","brother","grandfather"},
            {"daughter","sister","mother"},
            {"son","brother","grandfather"},
            {"daughter","sister","mother"},
            {"family","father","grandmother"},
            {"son","brother","grandfather"},

            {"machen", "sein","haben"},
            {"machen", "sein","haben"},
            {"machen", "sein","haben"},
            {"arbeiten","sehen", "schlafen"},
            {"arbeiten","sehen", "schlafen"},
            {"arbeiten","sehen", "schlafen"},
            {"trinken","essen","fühlen"},
            {"trinken","essen","fühlen"},
            {"trinken","essen","fühlen"},

            {"to do","to be","to have"},
            {"to do","to be","to have"},
            {"to do","to be","to have"},
            {"to work","to see","to feel"},
            {"to work","to see","to feel"},
            {"to drink","to eat","to sleep"},
            {"to drink","to eat","to sleep"},
            {"to drink","to eat","to sleep"},
            {"to work","to see","to feel"},

            {"one","five", "nine"},
            {"two","four","eight"},
            {"six","seven","three"},
            {"two","four","eight"},
            {"one","five", "nine"},
            {"six","seven","three"},
            {"six","seven","three"},
            {"two","four","eight"},
            {"one","five", "nine"},
            {"ten","five","seven"},

            {"ein","vier","sieben"},
            {"zwei","fünf","acht"},
            {"neun","sechs","drei"},
            {"ein","vier","sieben"},
            {"zwei","fünf","acht"},
            {"neun","sechs","drei"},
            {"ein","vier","sieben"},
            {"zwei","fünf","acht"},
            {"neun","sechs","drei"},
            {"zehn","zwei","neun"},

            {"Guten Morgen","Woher kommst du?","Ich bin ... Jahre alt."},
            {"Guten Tag!","Auf Wiedersehen!","Guten Morgen"},
            {"Guten Tag!","Auf Wiedersehen!","Guten Morgen"},
            {"Guten Morgen","Woher kommst du?","Ich bin ... Jahre alt."},
            {"Wie heißt du?","Ich heiße/ Ich bin...?","Ich wohne in..."},
            {"Wie heißt du?","Ich heiße/ Ich bin...?","Ich wohne in..."},
            {"Wie komme ich zu...?","Wie alt bist du?","Wo wohnst du?"},
            {"Guten Morgen","Woher kommst du?","Ich bin ... Jahre alt."},
            {"Wie komme ich zu...?","Wie alt bist du?","Wo wohnst du?"},
            {"Wie heißt du?","Ich heiße/ Ich bin...?","Ich wohne in..."},
            {"Wie komme ich zu...?","Wie alt bist du?","Wo wohnst du?"},
            {"Nach links.","Nach rechts.","Auf Wiedersehen!"},
            {"Nach links.","Nach rechts.","Auf Wiedersehen!"},
            {"Geradeaus gehen.","Ich habe mich verirrt.","Wie alt bist du?"},
            {"Geradeaus gehen.","Ich habe mich verirrt.","Wie alt bist du?"},


            {"Good morning!","Goodbye!","Good afternoon!"},
            {"Good morning!","Goodbye!","Good afternoon!"},
            {"Good morning!","Goodbye!","Good afternoon!"},
            {"Where are you from?","How old are you?","Where do you live?"},
            {"What's your name?","How can I get to...?","I live in..."},
            {"I'm ... years old.", "I'm lost.","My name is/ I am ..."},
            {"Where are you from?","How old are you?","Where do you live?"},
            {"I'm ... years old.", "I'm lost.","My name is/ I am ..."},
            {"Where are you from?","How old are you?","Where do you live?"},
            {"What's your name?","How can I get to...?","I live in..."},
            {"What's your name?","How can I get to...?","I live in..."},
            {"Turn left.","Go straight ahead.","Turn right."},
            {"Turn left.","Go straight ahead.","Turn right."},
            {"Turn left.","Go straight ahead.","Turn right."},
            {"I'm ... years old.", "I'm lost.","My name is/ I am ..."},

            {"das Fleisch","der Schinken"," das Hänchen"},
            {"das Fleisch","der Schinken"," das Hänchen"},
            {"das Fleisch","der Schinken"," das Hänchen"},
            {"die Kartoffel","die Karrotten","die Wurst"},
            {"der Apfel","die Orange","die Wassermelone"},
            {"der Apfel","die Orange","die Wassermelone"},
            {"die Erdbeere","die Himbeere","die Traube"},
            {"die Erdbeere","die Himbeere","die Traube"},
            {"die Erdbeere","die Himbeere","die Traube"},
            {"die Tomate","die Zwiebel","der Käse"},
            {"die Kartoffel","die Karrotten","die Wurst"},
            {"die Kartoffel","die Karrotten","die Wurst"},
            {"die Tomate","die Zwiebel","der Käse"},
            {"der Reis", "die Nudeln","die Birne"},
            {"der Apfel","die Orange","die Wassermelone"},
            {"die Tomate","die Zwiebel","der Käse"},
            {"die Milch","die Butter","das Brot"},
            {"die Milch","die Butter","das Brot"},
            {"der Reis", "die Nudeln","die Birne"},
            {"der Reis", "die Nudeln","die Birne"},
            {"die Milch","die Butter","das Brot"},

            {"chicken","sausage","meat"},
            {"chicken","sausage","meat"},
            {"strawbery","raspberry","ham"},
            {"chicken","sausage","meat"},
            {"apple","orange","grape"},
            {"apple","orange","grape"},
            {"strawbery","raspberry","ham"},
            {"strawbery","raspberry","ham"},
            {"apple","orange","grape"},
            {"tomato","potato","onion"},
            {"tomato","potato","onion"},
            {"carrot","watermelon","pear"},
            {"tomato","potato","onion"},
            {"carrot","watermelon","pear"},
            {"carrot","watermelon","pear"},
            {"butter","pasta","cheese"},
            {"milk","rice","bread"},
            {"butter","pasta","cheese"},
            {"milk","rice","bread"},
            {"butter","pasta","cheese"},
            {"milk","rice","bread"},

            {"airport","ATM","suitcase"},
            {"airport","ATM","suitcase"},
            {"flight","recepiton desk","museum"},
            {"railway station","bus stop","reservation"},
            {"railway station","bus stop","reservation"},
            {"ticket","passport","airplane ticket"},
            {"baggage","backpack","customs"},
            {"airport","ATM","suitcase"},
            {"baggage","backpack","customs"},
            {"baggage","backpack","customs"},
            {"ticket","passport","airplane ticket"},
            {"railway station","bus stop","reservation"},
            {"ticket","passport","airplane ticket"},
            {"flight","recepiton desk","museum"},
            {"flight","recepiton desk","museum"},


            {"der Flughafen","der Flug","der Bahnhof"},
            {"der Koffer","der Geldautomat","der Zoll"},
            {"das Museum", "die Rezeption","der Flugschein"},
            {"der Flughafen","der Flug","der Bahnhof"},
            {"die Fahrkarte","die Bushaltestelle","der Reisepass"},
            {"das Museum", "die Rezeption","der Flugschein"},
            {"das Gepäck","die Reservierung","der Rucksack"},
            {"der Koffer","der Geldautomat","der Zoll"},
            {"der Koffer","der Geldautomat","der Zoll"},
            {"das Gepäck","die Reservierung","der Rucksack"},
            {"die Fahrkarte","die Bushaltestelle","der Reisepass"},
            {"das Gepäck","die Reservierung","der Rucksack"},
            {"die Fahrkarte","die Bushaltestelle","der Reisepass"},
            {"der Flughafen","der Flug","der Bahnhof"},
            {"das Museum", "die Rezeption","der Flugschein"}




    };

    private String mCorrectAnswears[]={
            "city", "restaurant", "street", "post", "airport", "ATM", "cinema", "hospital", "museum", "parking", "swimming pool",
            "park", "library", "railway station", "bus stop",/*1*/    "die Stadt",/*2*/    "das Restaurant",/*3*/   "die Straße",
         /*4*/   "die Post",/*5*/     "der Flughafen",/*6*/      "der Geldautomat",/*7*/     "das Kino",/*8*/     "das Krankenhaus",
       /*9*/     "das Museum",/*10*/    "der Parkplatz",/*11*/    "das Schwimmbad",/*12*/     "der Park",/*13*/     "die Bibliothek",
            /*14*/     "der Bahnhof",/*15*/     "die Bushaltestelle",
            "der Kopf", "der Arm", "das Bein", "der Mund","die Nase", "das Auge", "das Ohr","das Haar","die Schulter", "das Knie",
            "head", "arm", "leg", "mouth", "nose", "eye","ear", "hair", "shoulder", "knee",
            "rot","gelb","grün","braun","grau", "weiß","schwarz","blau",
            "red", "yellow", "green", "brown","grey","white","black","blue", "das Fenster",
            "die Uhr",
            "die Lampe",
            "der Tisch",
            "der Sessel",
            "der Spiegel",
            "die Toilette",
            "das Bild",
            "der erste Stock",
            "der Kühlschrank",
            "das Geschirr",
            "die Küche",
            "das Badezimmer",
            "das Wohnzimmer",
            "die Möbel",
            "der Schreibtisch",
            "das Schlafzimmer",
            "die Tür",
            "window",
            "clock",
            "lamp",
            "table",
            "armchair",
            "mirror",
            "toilet",
            "picture",
            "1st floor",
            "fridge",
            "dishes",
            "kitchen",
            "bathroom",
            "living room",
            "furniture",
            "desk",
            "bedroom",
            "door",

            "das Englisch",
            "die Mathe",
            "das Französich",
            "das Spanisch",
            "das Deutsch",
            "die Physik",
            "die Chemie",
            "die Biologie",
            "die Kunst",
            "die Erdkunde",
            "der Sport",
            "der Lehrer/die Lehrerin",
            "das Klassenzimmer",

            "english",
            "mathematics",
            "french",
            "spanish",
            "german",
            "physics",
            "chemistry",
            "biology",
            "art",
            "geography",
            "physicacl education (PE)",
            "teacher",
            "classroom",


            "der Supermarkt",
            "das Lebensmittelgeschäft",
            "die Bäckerei",
            "die Konditorei",
            "die Drogerie",
            "die Buchhandlung",
            "das Schuhgeschäft",
            "die Perfümerie",
            "die Öffnungzeiten",
            "der Juwelierladen",
            "das Sonderangebot",
            "geschlossen",
            "geöffnet",
            "der Eingang",
            "der Ausgang",
            "die Kasse",
            "die Blumengeschäft",

            "supermarket",
            "grocer's",
            "baker's",
            "cake shop",
            "chemist's",
            "book shop",
            "shoe shop",
            "perfume shop",
            "opening hours",
            "jeweller's",
            "special offer",
            "closed",
            "open",
            "entrance",
            "exit",
            "cash desk",
            "florist's",

            "der Ski alpin",
            "das Bogenschießen",
            "der Baseball",
            "das Boxen",
            "das Bungee springen",
            "die Höhlenforschung",
            "der Radsport",
            "das Wasserspringen",
            "der Fußball",
            "das Skilaufen",
            "das Tischtennis",

            "alpine skiing",
            "archery",
            "baseball",
            "boxing",
            "bungee jumping",
            "caving",
            "cycling",
            "diving",
            "football/soccer",
            "skiing",
            "table tennis",

            "die Zeit",
            "die Stunde",
            "die Minute",
            "die Sekunde",
            "die Mitternacht",
            "der Mittag",
            "der Tag",
            "der Morgen",
            "der Nachmittag",
            "die Nacht",
            "gestern",
            "heute",
            "morgen",
            "der Frühling",
            "der Winter",
            "der Sommer",
            "der Herbst",

            "time",
            "hour",
            "minute",
            "second",
            "midnight",
            "midday",
            "day",
            "morning",
            "afternoon",
            "night",
            "yesterday",
            "today",
            "tommorow",
            "spring",
            "winter",
            "summer",
            "autumn",


            "die Familie",
            "der Vater",
            "die Mutter",
            "der Sohn",
            "die Tochter",
            "der Bruder",
            "die Schwester",
            "die Großmutter",
            "der Großvater",

            "family",
            "father",
            "mother",
            "son",
            "daughter",
            "brother",
            "sister",
            "grandmother",
            "grandfather",

            "machen",
            "sein",
            "haben",
            "arbeiten",
            "sehen",
            "schlafen",
            "trinken",
            "essen",
            "fühlen",

            "to do",
            "to be",
            "to have",
            "to work",
            "to see",
            "to sleep",
            "to drink",
            "to eat",
            "to feel",


            "one",
            "two",
            "three",
            "four",
            "five",
            "six",
            "seven",
            "eight",
            "nine",
            "ten",

            "ein",
            "zwei",
            "drei",
            "vier",
            "fünf",
            "sechs",
            "sieben",
            "acht",
            "neun",
            "zehn",

            "Guten Morgen",
            "Guten Tag!",
            "Auf Wiedersehen!",
            "Woher kommst du?",
            "Wie heißt du?",
            "Ich heiße/ Ich bin...?",
            "Wie alt bist du?",
            "Ich bin ... Jahre alt.",
            "Wo wohnst du?",
            "Ich wohne in...",
            "Wie komme ich zu...?",
            "Nach links.",
            "Nach rechts.",
            "Geradeaus gehen.",
            "Ich habe mich verirrt.",

            "Good morning!",
            "Good afternoon!",
            "Goodbye!",
            "Where are you from?",
            "What's your name?",
            "My name is/ I am ...",
            "How old are you?",
            "I'm ... years old.",
            "Where do you live?",
            "I live in...",
            "How can I get to...?",
            "Turn left.",
            "Turn right.",
            "Go straight ahead.",
            "I'm lost.",

            "das Fleisch",
            " das Hänchen",
            "der Schinken",
            "die Wurst",
            "der Apfel",
            "die Orange",
            "die Erdbeere",
            "die Himbeere",
            "die Traube",
            "die Tomate",
            "die Kartoffel",
            "die Karrotten",
            "die Zwiebel",
            "die Birne",
            "die Wassermelone",
            "der Käse",
            "die Milch",
            "die Butter",
            "der Reis",
            "die Nudeln",
            "das Brot",

            "meat",
            "chicken",
            "ham",
            "sausage",
            "apple",
            "orange",
            "strawbery",
            "raspberry",
            "grape",
            "tomato",
            "potato",
            "carrot",
            "onion",
            "pear",
            "watermelon",
            "cheese",
            "milk",
            "butter",
            "rice",
            "pasta",
            "bread",

            "airport",
            "ATM",
            "museum",
            "railway station",
            "bus stop",
            "airplane ticket",
            "backpack",
            "suitcase",
            "customs",
            "baggage",
            "ticket",
            "reservation",
            "passport",
            "flight",
            "recepiton desk",

            "der Flughafen",
            "der Geldautomat",
            "das Museum",
            "der Bahnhof",
            "die Bushaltestelle",
            "der Flugschein",
            "der Rucksack",
            "der Koffer",
            "der Zoll",
            "das Gepäck",
            "die Fahrkarte",
            "die Reservierung",
            "der Reisepass",
            "der Flug",
            "die Rezeption"






    };

    public String getQuestion(int a){
        String question=mQuestion[a];
        return question;
    }

    public String getChoice1(int a){
        String choice=mChoices[a][0];
        return choice;
    }

    public String getChoice2(int a){
        String choice=mChoices[a][1];
        return choice;
    }

    public String getChoice3(int a){
        String choice=mChoices[a][2];
        return choice;
    }

    public String getCorrectAnswear(int a){
        String answear=mCorrectAnswears[a];
        return answear;
    }




}
